# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 02:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_alerta', models.DateField(verbose_name=datetime.datetime(2017, 8, 9, 2, 18, 10, 910105, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='NivelAutorizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[(1, 'SUPERIOR'), (2, 'SUBCOMANDO'), (3, 'COMANDO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload', models.FileField(upload_to='uploads/%self.pk', verbose_name='Anexo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpDescricao', models.CharField(max_length=200)),
                ('tpModelo', models.TextField()),
                ('alerta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='part.Alerta')),
            ],
        ),
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('nivelAutorizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.NivelAutorizacao')),
            ],
        ),
        migrations.AddField(
            model_name='parte',
            name='tipoParte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.TipoParte'),
        ),
        migrations.AddField(
            model_name='parte',
            name='validacoes',
            field=models.ManyToManyField(to='part.Validacao'),
        ),
    ]
