# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0004_auto_20170815_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='qtd_validacoes',
        ),
        migrations.AddField(
            model_name='parte',
            name='data_fim',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parte',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoparte',
            name='qtd_validacoes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parte',
            name='boletim_interno',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
